name: Package-Alpha

on:
  push:
    tags:
      - '[0-9].[0-9][0-9].[0-9][0-9].[0-9]+'

jobs:

  release:

    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Clone project
        uses: actions/checkout@v1

      - name: Package for Retail
        uses: BigWigsMods/packager@v1
        with:
          args: -n "{package-name}-{project-version}-alpha{nolib}{classic}:{project-version}-alpha{classic}{nolib}"
