name: Release

on:
  push:
    tags:
      - '[0-9][0-9]?.[0-9][0-9].[0-9][0-9]'
      - '[0-9][0-9]?.[0-9][0-9].[0-9][0-9]-alpha-[0-9]+'

jobs:
  
  github:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v1
      - name: Package (release)
        uses: arkayenro/packager@v2


#      - name: Package (release-nolib)
#        uses: BigWigsMods/packager@v1
#        with:
#          args: -d -s

#  alphas:
#    if: ${{ contains(github.ref,'alpha') }}
#    runs-on: ubuntu-latest
#    env:
#      CF_API_KEY: ${{ secrets.CF_API_KEY }}
#      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
#      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
#      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
#    steps:
#      - name: Clone project
#        uses: actions/checkout@v1
#      - name: Package (alpha)
#        uses: BigWigsMods/packager@v1
#        with:
#          args: -d -w 0
          
# -w 0 = not wowinterface, it doesnt support alpha/beta, only release
