name: Packager-Stable

on:
  push:
    tags:
      - '[0-9][0-9]?.[0-9][0-9].[0-9][0-9]'
      - '[0-9][0-9]?.[0-9][0-9].[0-9][0-9]-alpha-[0-9]+'

jobs:
  
  release:
    if: ${{ !contains(github.ref,'alpha') }}
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v1
      - name: Package (release)
        uses: BigWigsMods/packager@v1
#        with:
#          args: -n "{package-name}-{project-version}{nolib}:{project-version}"
      - name: Package (release-nolib)
        uses: BigWigsMods/packager@v1
        with:
          args: -s
# 

  alpha:
    if: ${{ contains(github.ref,'alpha') }}
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v1
      - name: Package (alpha)
        uses: BigWigsMods/packager@v1
        with:
          args: -w 0 -n "ArkTest-{project-version}:{project-version}"
          
# -w 0 = not wowinterface, it doesnt support alpha/beta, only release
        
        
#      - name: Package nolib
#        uses: BigWigsMods/packager@v1
#        with:
#          args: -s # nolib
