name: Packager

on:
  push:
    tags:
      - '[0-9][0-9]?.[0-9][0-9].[0-9][0-9]'
      - '[0-9][0-9]?.[0-9][0-9].[0-9][0-9]-alpha-[0-9]+'
      - '[0-9][0-9]?.[0-9][0-9].[0-9][0-9]-beta-[0-9]+'

jobs:
  
  release:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      
    steps:
      - name: Clone project
        uses: actions/checkout@v1
        
      - name: Package (release)
        if: ${{ !(contains(github.ref,'alpha') || contains(github.ref,'beta')) }}
        uses: arkayenro/packager@v2
        
      - name: Package (alpha/beta)
        if: ${{ contains(github.ref,'alpha') || contains(github.ref,'beta') }}
        uses: arkayenro/packager@v2
        with: # wowinterface doesnt support alpha/beta so dont upload them there
          args: -w 0
