name: Packager-Stable

on:
  push:
    tags:
      - '[0-9][0-9]?.[0-9][0-9].[0-9][0-9]'
      - '[0-9][0-9]?.[0-9][0-9].[0-9][0-9]-alpha-[0-9]+'

# a workflow is built up as jobs, and within these jobs are steps
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
          echo ${{ github.ref }}
    
  mainline:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v1
      - name: Package
        uses: BigWigsMods/packager@v1.0.3
        
        
#        with:
#          args: -n "{package-name}-{project-version}-{game-type}{alpha}{beta}{nolib}:{project-version}-{game-type}{alpha}{beta}{nolib}"
        
#      - name: Package nolib
#        uses: BigWigsMods/packager@v1
#        with:
#          args: -s -n "{package-name}-{project-version}-{game-type}{alpha}{beta}{nolib}:{project-version}-{game-type}{alpha}{beta}{nolib}"
