name: Packager-Stable

on:
  push:
    tags:
      - '[0-9].[0-9][0-9].[0-9][0-9]**'

# a workflow is built up as jobs, and within these jobs are steps
jobs:

  # "release" is a job, you can name it anything you want
  release:

    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Clone project
        uses: actions/checkout@v1

      - name: Package for Retail
        uses: BigWigsMods/packager@v1
        
#      - name: Package for Retail
#        uses: BigWigsMods/packager@v1
#        with:
#          args: -g classic
